---
abstract: 'date manipulation routines'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Manip
provides:
  Date::Manip:
    file: lib/Date/Manip.pm
    version: 5.56
  Date::Manip::DM5abbrevs:
    file: lib/Date/Manip/DM5abbrevs.pm
    version: 6.08
requires:
  Carp: 0
  IO::File: 0
  perl: 5.001
resources:
  license: http://dev.perl.org/licenses/
version: 5.56
