#!/bin/sh

if [ "$1" = "-T" ]; then
   taint="-T -I../lib -I."
   shift
else
   taint=
fi

tests=$1
if [ -z "$tests" ]; then
   tests="all"
fi

# Date::Manip::TZdata

if [ "$tests" = "all"  -o  "$tests" = "tzdata" ]; then
   echo ""
   echo "Date::Manip::TZdata..."
   echo ""
   for test in tzdata.*.tx ;do
     perl $taint $test 1
   done
fi

# Date::Manip::Base

if [ "$tests" = "all"  -o  "$tests" = "base" ]; then
   echo ""
   echo "Date::Manip::Base..."
   echo ""
   for test in base.*.t ;do
     perl $taint $test 1
   done
fi

# Date::Manip::TZ

if [ "$tests" = "all"  -o  "$tests" = "tz" ]; then
   echo ""
   echo "Date::Manip::TZ..."
   echo ""
   for test in tz.*.t ;do
     perl $taint $test 1
   done
fi

# Date::Manip::Date

if [ "$tests" = "all"  -o  "$tests" = "date" ]; then
   echo ""
   echo "Date::Manip::Date..."
   echo ""
   for test in date.*.t ;do
     perl $taint $test 1
   done
fi

# Date::Manip::Delta

if [ "$tests" = "all"  -o  "$tests" = "delta" ]; then
   echo ""
   echo "Date::Manip::Delta..."
   echo ""
   for test in delta.*.t ;do
     perl $taint $test 1
   done
fi

# Date::Manip::Recur

if [ "$tests" = "all"  -o  "$tests" = "recur" ]; then
   echo ""
   echo "Date::Manip::Recur..."
   echo ""
   for test in recur.*.t ;do
     perl $taint $test 1
   done
fi

# Date::Manip

if [ "$tests" = "all"  -o  "$tests" = "orig" ]; then
   echo ""
   echo "Date::Manip..."
   echo ""
   for test in orig.*.t ;do
     perl $taint $test 1
   done
fi

