#!/usr/bin/perl

use JSON;

$curry   = ( localtime(time) )[5] + 1900;

my $json = new JSON;
$json->utf8(0);
$json->pretty();

my @mod = qw(
              catalan
              danish
              dutch
              english
              french
              german
              italian
              norwegian
              polish
              portugue
              romanian
              russian
              spanish
              swedish
              turkish
            );

foreach my $mod (@mod) {
   eval "require Date::Manip::Lang::${mod}";
   my $lang  = ${ "Date::Manip::Lang::${mod}::Language" };
   my $name  = ${ "Date::Manip::Lang::${mod}::LangName" };
   my $year0 = ${ "Date::Manip::Lang::${mod}::YearAdded" };
   my @enc   = @{ "Date::Manip::Lang::${mod}::Encodings" };
   my $json  = $json->encode($lang);

   open(OUT,"> ../$mod.pm");
   print OUT << "EOF";
package Date::Manip::Lang::$mod;
# Copyright (c) $year0-$curry Sullivan Beck. All rights reserved.
# This program is free software; you can redistribute it and/or modify it
# under the same terms as Perl itself.

########################################################################
########################################################################

require 5.010000;
use JSON;

use strict;
use warnings;

our(\$VERSION);
\$VERSION='6.31';

our(\$Language,\@Encodings,\$LangName,\$YearAdded);
\@Encodings = qw(@enc);
\$LangName  = "$name";
\$YearAdded = $year0;

my \@in     = <DATA>;
\$Language  = JSON->new->utf8(0)->decode(join("",\@in));

1;
__DATA__
$json
EOF
   close(OUT);
}

